#!/bin/bash
if [ -z $1 ];then echo 'usage: mass-storage <path>';exit;fi
if ! [ -f $1 ];then echo 'error: device not found';exit;fi

echo '0' >/sys/class/android_usb/android0/enable
echo $1 >/sys/class/android_usb/android0/f_mass_storage/lun/file
echo 'mass_storage' >/sys/class/android_usb/android0/functions
echo '1' >/sys/class/android_usb/android0/enable
